[[server]]
    port = 4242
    address = "0.0.0.0"
    server_name = ["localhost"]
    body_size = 1048576

    [[server.location]]
        route = "/"
        root = "www/"
        index = "index.html"
        allowed_methods = ["POST", "GET", "DELETE"]
        cgi_extension = ["py", "sh", "pl"]
        uploadable = true
        cgi_dir = "cgi/upload/"

    [[server.location]]
        route = "error_pages/"
        root = "www/"
        error_page = "error.html"
