[[server]]
    port = 4206
    address = "127.0.0.1"
    server_name = ["www.example.com"]
    body_size = 1048576
    cgi_extension = ["py", "sh", "pl"]
    cgi_dir = "/cgi"

    [[server.location]]
        route = "/"
        root = "/www"
        index = "index.html"
        allowed_methods = ["POST", "GET", "DELETE"]
        uploadable = true
        autoindex = true

    [[server.location]]
        route = "/status"
        error_page = "error.html"
        redirect = "redirect.html"
    
    [[server.location]]
        route = "/cookies"
        cookie_page = "cookies.html"
